### ISSUE TITLE
Test failure on Human-Readable Prefixes

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/bech32#27]
This was reproduced on MacOS:

```
Codec.Binary.Bech32.TH
  Quasi-Quotations
    Human-Readable Prefixes
      Parsing valid human-readable prefixes should succeed.
        "!"
        "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        "addr"
      Parsing invalid human-readable prefixes should fail.
        "" FAILED [1]
        "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" FAILED [2]
        "  " FAILED [3]
        "\DEL\DEL" FAILED [4]
```

**Comment by newhoggy** [comment]
Given that there is a potential platform specific failure, I'd like to modify the Github Actions build to do a Matrix build over MacOS and Windows.

**Comment by newhoggy** [comment]
Turns out it's not a platform problem, but a GHC version problem.  This PR shows the code compiles against Linux, MacOS and Windows when using `ghc-8.6.5`, but it doesn't not compile against `ghc-8.10.2`

**Comment by rvl** [comment]
So it works on `ghc-8.6.5` (all platforms) and fails on `ghc-8.10.2` (all platforms).
Did you mean it compiles but tests fail, or does it not compile at all for `ghc-8.10.2`?

If the latter, is this simply due to `-Werror`?

If the former, is the failure actually due to GHC itself, or is it because the cabal solver has selected a different set of package versions (and perhaps a quickcheck generator change has caused this test failure, or something like that).

**Comment by rvl** [comment]
No response, closing.
